// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClcNY0fu_cOrQ-yKmAWirWm4AjZDy-Wdw',
    appId: '1:111965627176:web:821a90963995b479d3661d',
    messagingSenderId: '111965627176',
    projectId: 'analisador-texto-1764695357',
    authDomain: 'analisador-texto-1764695357.firebaseapp.com',
    storageBucket: 'analisador-texto-1764695357.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVQY432edjIRNnEcP0RAU9HdQ3Hn0ju8',
    appId: '1:111965627176:ios:2438909dd4cff160d3661d',
    messagingSenderId: '111965627176',
    projectId: 'analisador-texto-1764695357',
    storageBucket: 'analisador-texto-1764695357.firebasestorage.app',
    iosBundleId: 'com.example.analisadorTexto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLVQY432edjIRNnEcP0RAU9HdQ3Hn0ju8',
    appId: '1:111965627176:ios:2438909dd4cff160d3661d',
    messagingSenderId: '111965627176',
    projectId: 'analisador-texto-1764695357',
    storageBucket: 'analisador-texto-1764695357.firebasestorage.app',
    iosBundleId: 'com.example.analisadorTexto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClcNY0fu_cOrQ-yKmAWirWm4AjZDy-Wdw',
    appId: '1:111965627176:web:0e585103fc35af95d3661d',
    messagingSenderId: '111965627176',
    projectId: 'analisador-texto-1764695357',
    authDomain: 'analisador-texto-1764695357.firebaseapp.com',
    storageBucket: 'analisador-texto-1764695357.firebasestorage.app',
  );
}
